# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/bio-routing/bio-rd
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure -v

      - run: go test -v -cover -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)

      - run: .circleci/build-examples
      - run: .circleci/check-gofmt
